In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/elasawy/student-score/Student_Performance.csv

In [2]:
data= pd.read_csv('/kaggle/input/datasets/elasawy/student-score/Student_Performance.csv')

In [3]:
data.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data["Extracurricular Activities"]=le.fit_transform(data["Extracurricular Activities"])

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hours Studied                     10000 non-null  int64
 1   Previous Scores                   10000 non-null  int64
 2   Extracurricular Activities        10000 non-null  int64
 3   Sleep Hours                       10000 non-null  int64
 4   Sample Question Papers Practiced  10000 non-null  int64
 5   Performance Index                 10000 non-null  float64
dtypes: float64(1), int64(5)
memory usage: 468.9 KB

In [12]:
data.corr()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
Hours Studied,1.000000,-0.012390,0.003873,0.001245,0.017463,0.373730
Previous Scores,-0.012390,1.000000,0.008369,0.005944,0.007888,0.915189
Extracurricular Activities,0.003873,0.008369,1.000000,-0.023284,0.013103,0.024525
Sleep Hours,0.001245,0.005944,-0.023284,1.000000,0.003990,0.048106
Sample Question Papers Practiced,0.017463,0.007888,0.013103,0.003990,1.000000,0.043268
Performance Index,0.373730,0.915189,0.024525,0.048106,0.043268,1.000000

In [16]:
new_data=data.drop (['Sleep Hours'],axis=1)

In [19]:
new_data.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sample Question Papers Practiced,Performance Index
0,7,99,1,1,91.0
1,4,82,0,2,65.0
2,8,51,1,2,45.0
3,5,52,1,2,36.0
4,7,75,0,5,66.0

# split data (train & test)

In [25]:
train_data= new_data.loc[:8000,:]
x_train= train_data.drop (["Performance Index"], axis=1)
y_train= train_data["Performance Index"]
##########
test_data= new_data.loc[8001:,:]
x_test= test_data.drop (["Performance Index"], axis=1)
y_test= test_data["Performance Index"]

# Train the mode

In [26]:
from sklearn.linear_model import LinearRegression
le = LinearRegression()
le.fit(x_train,y_train)

LinearRegression()

# acurcy

In [28]:
le.score(x_test,y_test)

0.9863498421449068